# Copyright 2016--2022 Lightbits Labs Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.22-alpine3.19 AS builder

RUN apk update && \
    apk add --no-cache \
    curl \
    docker-cli \
    bash \
    make \
    git \
    g++ \
    musl-dev \
    util-linux-dev \
    linux-headers

ENV UNAME=app

ARG GID=1000
ARG UID=1000
ARG DOCKER_GID=998

RUN addgroup -g $GID $UNAME
# on alpine ping group is coliding with docker-group on id 999 - delete it if exists
RUN getent group ping && delgroup ping
RUN addgroup -g $DOCKER_GID docker
RUN adduser --disabled-password -u $UID -G $UNAME -G docker $UNAME

COPY . /go/src/github.com/lightbitslabs/discovery-client
WORKDIR /go/src/github.com/lightbitslabs/discovery-client
RUN make build/discovery-client


FROM alpine:3.19

LABEL maintainers="Lightbits Labs" \
      description="NVMeTCP Discovery Client Service" \
      version.rel="UNKNOWN" \
      version.git="UNKNOWN" \
      version.build.host="UNKNOWN" \
      version.build.time="UNKNOWN" \
      version.build.id="UNKNOWN"

RUN apk update && \
    apk add --no-cache \
    util-linux

RUN mkdir -p /etc/{discovery-client,nvme}
COPY --from=builder /go/src/github.com/lightbitslabs/discovery-client/etc/discovery-client/discovery-client.yaml /etc/discovery-client/

COPY --from=builder /go/src/github.com/lightbitslabs/discovery-client/build/discovery-client /discovery-client

ENTRYPOINT ["/discovery-client"]
CMD ["serve"]
